### ISSUE TITLE
individual translation, Google suitability, manual control

### ISSUE THREAD

**Issue by Fanni-Portier** [numero2/contao-deepl#3]
Can I specify entire pages and modules (News, Catalog Manager) to be translated or do I still have to process the translations myself?

Are the pages then also created to be indexed by Google?

Can the translations be edited manually?

**Comment by bennyborn** [comment]
This extension only provides the function to translate individual fields. If you copy an entire page you'd still have to go through articles and content elements manually and let each field translate.

Of course the pages will still be indexed by search engines and you can change all the translations any time you want 😉
