### ISSUE TITLE
Probleme bei verschachteltem ContentElement

### ISSUE THREAD

**Issue by stefan-melz** [numero2/contao-deepl#4]
Bei verschachtelten CE ist parentTable tl_content, daher gibt der resolver hier ein false zurück. Da müsste man dann eventeull eine ebene höher schauen bis tl_article kommt, falls überhaupt nötig. Dafür habe ich zu wenig recherchiert.

**Comment by bennyborn** [comment]
Für die allgemeine `tl_content` wäre es recht einfach zu fixen, allerdings klappts dann bei den News und Events so nicht. 
Da brauche ich ein paar Minuten mehr Ruhe, aber habs auf dem Zettel 😉

**Comment by bennyborn** [comment]
Sollte jetzt mit 1.0.4 behoben sein.
